FROM node:latest
WORKDIR /stokbarang-backend

RUN mkdir -p uploads

COPY package*.json ./
RUN npm install

ENV KATEGORI_DBHOST=192.168.7.44
ENV KATEGORI_DBUSER=root
ENV KATEGORI_DBPASSWORD=Ijinmasuk2022
ENV KATEGORI_DBNAME=gudang

ENV DATABARANG_DBHOST=192.168.7.44
ENV DATABARANG_DBUSER=root
ENV DATABARANG_DBPASSWORD=Ijinmasuk2022
ENV DATABARANG_DBNAME=gudang

COPY . .
EXPOSE 3001
CMD ["node", "index.js"]
