FROM node:latest
WORKDIR /stokbarang-backend

COPY package*.json ./
RUN npm install

ENV KATEGORI_DBHOST=13.229.43.83
ENV KATEGORI_DBUSER=kelompok3
ENV KATEGORI_DBPASSWORD=k3l0mp0k3
ENV KATEGORI_DBNAME=gudang

ENV DATABARANG_DBHOST=13.229.43.83
ENV DATABARANG_DBUSER=kelompok3
ENV DATABARANG_DBPASSWORD=k3l0mp0k3
ENV DATABARANG_DBNAME=gudang

COPY . .
EXPOSE 3001
CMD ["node", "index.js"]
